# Generated by Django 5.0.1 on 2024-02-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_is_shop_owner_customuser_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='estate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customuser',
            name='house_number',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
