# Generated by Django 5.0.1 on 2024-04-17 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Refill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_liters",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Amount in Litres"
                    ),
                ),
                (
                    "amount_money",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Amount in Kenyan Shillings",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="refills",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Refill",
                "verbose_name_plural": "Refills",
                "ordering": ["-created_at"],
            },
        ),
    ]
